'use client';
import {useRef,useState} from 'react';
import * as XLSX from 'xlsx';
import {Users,ChevronRight,FileSpreadsheet,Download,Upload,CheckCircle2,AlertCircle,Database} from 'lucide-react';
import {sb,norm} from './client';

function Notice({kind='success',children}:any){return <div className={'notice '+kind}>{kind==='success'?<CheckCircle2/>:<AlertCircle/>}<span>{children}</span></div>}
function parseDate(v:any){if(v instanceof Date&&!isNaN(v.getTime()))return v.toISOString();if(typeof v==='number'){const p=XLSX.SSF.parse_date_code(v);if(p)return new Date(p.y,p.m-1,p.d,p.H||0,p.M||0,p.S||0).toISOString()}const s=String(v||'').trim();const m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})(?:[ ,.T]+(\d{1,2})[:.](\d{2}))?/);if(m)return new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),Number(m[4]||0),Number(m[5]||0)).toISOString();const d=new Date(s);return isNaN(d.getTime())?new Date().toISOString():d.toISOString()}
function signedNumber(v:any){const n=Number(String(v??'').replace(/[^0-9.-]/g,''));return Number.isFinite(n)?Math.round(n):0}
function officialRecordTemplate(){const wb=XLSX.utils.book_new();const headers=['No.','Nama','Kelas','Tanggal','Jenis Kejadian','Poin','Kategori','Kronologi','Pencatat'];const sheets:any={Pelanggaran:[[...headers],[1,'Nama Siswa','7A','29/08/2026','Terlambat masuk sekolah',2,'Kerajinan & Kehadiran','Datang setelah bel masuk','Nama Guru']],Prestasi:[[...headers],[1,'Nama Siswa','7A','29/08/2026','Mewakili sekolah dalam kegiatan',10,'PRESTASI','Mewakili sekolah dalam lomba','Nama Guru']],Sangsi:[[...headers],[1,'Nama Siswa','7A','29/08/2026','Pelanggaran yang ditindaklanjuti','','Pelanggaran yang ditindaklanjuti','Surat pernyataan / panggilan orang tua','Nama Guru']]};for(const [name,rows] of Object.entries(sheets)){const ws=XLSX.utils.aoa_to_sheet(rows as any[][]);ws['!cols']=[{wch:6},{wch:25},{wch:10},{wch:15},{wch:38},{wch:10},{wch:28},{wch:46},{wch:28}];XLSX.utils.book_append_sheet(wb,ws,name)}XLSX.writeFile(wb,'CATATAN DISIPLIN PELANGGARAN.xlsx')}
function get(row:any,key:string){for(const [k,v] of Object.entries(row||{}))if(norm(k)===norm(key))return v;return ''}

export default function ImportExcel({school,students,master,reload,setActive}:any){
 const [fileName,setFileName]=useState(''),[rows,setRows]=useState<any[]>([]),[status,setStatus]=useState(''),[busy,setBusy]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 async function readExcel(file:File){setFileName(file.name);setStatus('');try{const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const out:any[]=[];for(const sn of wb.SheetNames){const n=norm(sn);let base:'violation'|'achievement'|'sanction'|null=n==='pelanggaran'?'violation':n==='prestasi'?'achievement':(n==='sangsi'||n==='sanksi')?'sanction':null;if(!base)continue;const data:any[]=XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:'',raw:true});for(const r of data){const studentName=String(get(r,'Nama')).trim();const className=String(get(r,'Kelas')).trim();const itemName=String(get(r,'Jenis Kejadian')).trim();if(!studentName||!itemName)continue;const rawPoints=signedNumber(get(r,'Poin'));const category=String(get(r,'Kategori')).trim();let type=base;if(base==='violation'&&(rawPoints<0||norm(category)==='prestasi'))type='achievement';out.push({type,source_sheet:sn,student_name:studentName,class_name:className,date:parseDate(get(r,'Tanggal')),item_name:itemName,points:Math.abs(rawPoints),category,notes:String(get(r,'Kronologi')).trim(),recorder:String(get(r,'Pencatat')).trim()})}}setRows(out);if(!out.length)setStatus('Tidak menemukan catatan valid. Gunakan sheet Pelanggaran, Prestasi, dan Sangsi dengan header resmi template.')}catch(e:any){setStatus(e.message||'File tidak dapat dibaca.')}}
 function findStudent(r:any){const exact=students.filter((x:any)=>norm(x.name)===norm(r.student_name)&&(!r.class_name||norm(x.class_name)===norm(r.class_name)));if(exact.length===1)return exact[0];const byName=students.filter((x:any)=>norm(x.name)===norm(r.student_name));return byName.length===1?byName[0]:null}
 async function runImport(){if(!school||!rows.length)return;setBusy(true);setStatus('');try{const linked=rows.map((r:any)=>({...r,student:findStudent(r)}));const unmatched=linked.filter((r:any)=>!r.student),usable=linked.filter((r:any)=>r.student);const masterMap=new Map<string,any>(master.map((m:any)=>[`${m.type}|${norm(m.name)}`,m] as [string,any]));const needed:any[]=[];const seen=new Set<string>();for(const r of usable){const key=`${r.type}|${norm(r.item_name)}`;if(!masterMap.has(key)&&!seen.has(key)){seen.add(key);needed.push({school_id:school.id,type:r.type,name:r.item_name,category:r.category||null,points:r.points||0,min_points:r.type==='sanction'?r.points||0:null,is_active:true})}}if(needed.length){const created=await sb.from('master_items').insert(needed).select('*');if(created.error)throw created.error;for(const m of created.data||[])masterMap.set(`${m.type}|${norm(m.name)}`,m)}const incidentRows:any[]=[],actionRows:any[]=[];for(const r of usable){const mi:any=masterMap.get(`${r.type}|${norm(r.item_name)}`);if(r.type==='sanction'){actionRows.push({school_id:school.id,student_id:r.student.id,sanction_master_id:mi?.id||null,sanction_name_snapshot:r.item_name,threshold_points:r.points||0,status:'pending',notes:[r.notes,r.category?`Kategori: ${r.category}`:'',r.recorder?`Pencatat: ${r.recorder}`:'',`Tanggal: ${new Date(r.date).toLocaleDateString('id-ID')}`].filter(Boolean).join(' · ')||null})}else incidentRows.push({school_id:school.id,student_id:r.student.id,type:r.type,master_item_id:mi?.id||null,item_name_snapshot:r.item_name,category_snapshot:r.category||mi?.category||null,points_snapshot:r.points||mi?.points||0,occurred_at:r.date,chronology:r.notes||null,recorder_name:r.recorder||null})}if(incidentRows.length){const a=await sb.from('incidents').insert(incidentRows);if(a.error)throw a.error}if(actionRows.length){const a=await sb.from('student_actions').insert(actionRows);if(a.error)throw a.error}await sb.from('import_history').insert({school_id:school.id,import_type:'official_discipline_records',file_name:fileName||'Excel',summary:{found:rows.length,imported:usable.length,unmatched:unmatched.length,new_master:needed.length,incidents:incidentRows.length,sanctions:actionRows.length}});setStatus(`Import selesai: ${usable.length} catatan masuk, ${needed.length} master baru dibuat${unmatched.length?`, ${unmatched.length} dilewati karena Nama + Kelas tidak cocok`:''}.`);setRows([]);setFileName('');await reload()}catch(e:any){setStatus(e.message||'Import gagal.')}finally{setBusy(false)}}
 const preview=rows.slice(0,10),matchedCount=rows.filter((r:any)=>Boolean(findStudent(r))).length;
 return <div className="page"><div className="pageLead"><div><span className="eyebrow purple">FORMAT RESMI EXCEL</span><h1>Import & Export</h1><p>Catatan dibaca sesuai template resmi: sheet <b>Pelanggaran</b>, <b>Prestasi</b>, dan <b>Sangsi</b>; header tetap No., Nama, Kelas, Tanggal, Jenis Kejadian, Poin, Kategori, Kronologi, Pencatat.</p></div></div>{status&&<Notice kind={status.includes('selesai')?'success':'warning'}>{status}</Notice>}<div className="importCards"><button className="importCard" onClick={()=>setActive('Data Siswa')}><div className="importIcon"><Users/></div><div><h3>Data Siswa</h3><p>Gunakan TAMPLET SISWA DATA.xlsx. Nama sheet otomatis menjadi kelas.</p><span>Buka Data Siswa <ChevronRight/></span></div></button><button className="importCard" onClick={()=>setActive('Master Data')}><div className="importIcon"><Database/></div><div><h3>Master Data</h3><p>Master baru dari catatan Excel akan dibuat otomatis bila belum tersedia.</p><span>Buka Master Data <ChevronRight/></span></div></button><button className="importCard" onClick={officialRecordTemplate}><div className="importIcon"><Download/></div><div><h3>Download Template Catatan</h3><p>Format Pelanggaran / Prestasi / Sangsi sesuai standar yang ditetapkan.</p><span>Download Excel <Download/></span></div></button></div><div className="panel importWorkspace"><div className="panelTitle"><div><h3>Import CATATAN DISIPLIN PELANGGARAN.xlsx</h3><p>Siswa dicocokkan menggunakan Nama + Kelas. Jenis kejadian yang belum ada akan otomatis menjadi Master Data.</p></div><span className="badge">Format terkunci</span></div><button className="dropzone" onClick={()=>fileRef.current?.click()}><FileSpreadsheet/><b>{fileName||'Pilih CATATAN DISIPLIN PELANGGARAN.xlsx'}</b><span>Sheet Pelanggaran · Prestasi · Sangsi</span></button><input ref={fileRef} hidden type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&readExcel(e.target.files[0])}/>{rows.length>0&&<div className="previewBox"><div className="panelTitle"><div><h3>Preview Import</h3><p>{rows.length} catatan terbaca · {matchedCount} siswa cocok</p></div></div>{preview.map((r:any,i)=><div className="previewRow" key={i}><b>{r.student_name} · {r.class_name||'-'}</b><span>{r.source_sheet} · {r.item_name} · {r.type==='achievement'?'-':'+'}{r.points} poin</span></div>)}</div>}<div className="templateStrip"><div><b>Catatan penting</b><span>Poin negatif atau kategori PRESTASI pada sheet Pelanggaran otomatis dibaca sebagai prestasi/pengurang poin.</span></div><button className="ghost actionBtn" onClick={officialRecordTemplate}><Download/> Download Template</button></div><div className="modalActions"><button className="primary" disabled={!rows.length||busy} onClick={runImport}><Upload/> {busy?'Mengimport...':'Import Catatan Sekarang'}</button></div></div></div>;
}
