'use client';
import {useRef,useState} from 'react';
import * as XLSX from 'xlsx';
import {Users,TriangleAlert,ChevronRight,FileSpreadsheet,Download,Upload,CheckCircle2,AlertCircle,Database} from 'lucide-react';
import {sb,norm,val,num,downloadBook} from './client';

function Notice({kind='success',children}:any){return <div className={'notice '+kind}>{kind==='success'?<CheckCircle2/>:<AlertCircle/>}<span>{children}</span></div>}
function parseDate(v:any){if(v instanceof Date&&!isNaN(v.getTime()))return v.toISOString();if(typeof v==='number'){const p=XLSX.SSF.parse_date_code(v);if(p)return new Date(p.y,p.m-1,p.d,p.H||0,p.M||0,p.S||0).toISOString()}const s=String(v||'').trim();const m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})(?:\s+(\d{1,2}):(\d{2}))?/);if(m)return new Date(Number(m[3]),Number(m[2])-1,Number(m[1]),Number(m[4]||0),Number(m[5]||0)).toISOString();const d=new Date(s);return isNaN(d.getTime())?new Date().toISOString():d.toISOString()}

export default function ImportExcel({school,students,master,reload,setActive}:any){
 const [fileName,setFileName]=useState('');
 const [rows,setRows]=useState<any[]>([]);
 const [status,setStatus]=useState('');
 const [busy,setBusy]=useState(false);
 const fileRef=useRef<HTMLInputElement>(null);
 function downloadTemplate(){const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Nama Siswa','NIS','Kelas','Tanggal','Jenis Pelanggaran','Poin','Kategori','Kronologi','Pencatat'],['Andi Pratama','12345','7A','29/08/2026 08:00','Terlambat masuk sekolah',2,'Kedisiplinan','Datang setelah bel masuk','Budi Santoso']]),'Pelanggaran');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Nama Siswa','NIS','Kelas','Tanggal','Jenis Prestasi','Poin','Kategori','Keterangan','Pencatat'],['Andi Pratama','12345','7A','28/08/2026','Juara 1 Lomba',10,'Akademik','Lomba tingkat kota','Budi Santoso']]),'Prestasi');XLSX.utils.book_append_sheet(wb,XLSX.utils.aoa_to_sheet([['Nama Siswa','NIS','Kelas','Tanggal','Nama Sanksi','Poin','Keterangan','Pencatat'],['Andi Pratama','12345','7A','29/08/2026','Teguran tertulis',10,'Tindak lanjut sekolah','Budi Santoso']]),'Sanksi');downloadBook(wb,'Template-Catatan-Siswa-Bantu-Beres.xlsx')}
 async function readExcel(file:File){setFileName(file.name);setStatus('');const buf=await file.arrayBuffer();const wb=XLSX.read(buf,{type:'array',cellDates:true});const out:any[]=[];for(const sn of wb.SheetNames){const n=norm(sn);const type:'violation'|'achievement'|'sanction'=n.includes('prestasi')?'achievement':n.includes('sanksi')?'sanction':'violation';const data:any[]=XLSX.utils.sheet_to_json(wb.Sheets[sn],{defval:''});for(const r of data){const studentName=String(val(r,['nama siswa','nama','siswa','nama lengkap'])).trim();const nis=String(val(r,['nis','nomor induk siswa'])).trim();if(!studentName&&!nis)continue;const itemNames=type==='violation'?['jenis pelanggaran','pelanggaran','nama pelanggaran']:type==='achievement'?['jenis prestasi','prestasi','nama prestasi']:['nama sanksi','sanksi','jenis sanksi'];const itemName=String(val(r,itemNames)).trim();if(!itemName)continue;out.push({type,student_name:studentName,nis,class_name:String(val(r,['kelas','rombel'])).trim(),date:parseDate(val(r,['tanggal','tanggal kejadian','waktu','tanggal catatan'])),item_name:itemName,points:num(val(r,['poin','point','bobot'])),category:String(val(r,['kategori','category'])).trim(),notes:String(val(r,['kronologi','keterangan','catatan','notes'])).trim(),recorder:String(val(r,['pencatat','guru','petugas','oleh'])).trim()})}}setRows(out);if(!out.length)setStatus('Tidak menemukan catatan yang valid. Gunakan template resmi atau periksa nama kolom.')}
 function findStudent(r:any){if(r.nis){const s=students.find((x:any)=>norm(x.nis)===norm(r.nis));if(s)return s}const exact=students.filter((x:any)=>norm(x.name)===norm(r.student_name)&&(!r.class_name||norm(x.class_name)===norm(r.class_name)));if(exact.length===1)return exact[0];const byName=students.filter((x:any)=>norm(x.name)===norm(r.student_name));return byName.length===1?byName[0]:null}
 async function runImport(){if(!school||!rows.length)return;setBusy(true);setStatus('');try{const linked=rows.map(r=>({...r,student:findStudent(r)}));const unmatched=linked.filter(r=>!r.student);const usable=linked.filter(r=>r.student);const masterMap=new Map(master.map((m:any)=>[`${m.type}|${norm(m.name)}`,m]));const needed:any[]=[];const seen=new Set<string>();for(const r of usable){const key=`${r.type}|${norm(r.item_name)}`;if(!masterMap.has(key)&&!seen.has(key)){seen.add(key);needed.push({school_id:school.id,type:r.type,name:r.item_name,category:r.category||null,points:r.points||0,min_points:r.type==='sanction'?r.points||0:null,is_active:true})}}if(needed.length){const created=await sb.from('master_items').insert(needed).select('*');if(created.error)throw created.error;for(const m of created.data||[])masterMap.set(`${m.type}|${norm(m.name)}`,m)}const incidentRows:any[]=[];const actionRows:any[]=[];for(const r of usable){const mi=masterMap.get(`${r.type}|${norm(r.item_name)}`);if(r.type==='sanction'){actionRows.push({school_id:school.id,student_id:r.student.id,sanction_master_id:mi?.id||null,sanction_name_snapshot:r.item_name,threshold_points:r.points||0,status:'pending',notes:[r.notes,r.recorder?`Pencatat: ${r.recorder}`:'',`Tanggal catatan: ${new Date(r.date).toLocaleDateString('id-ID')}`].filter(Boolean).join(' · ')||null})}else{incidentRows.push({school_id:school.id,student_id:r.student.id,type:r.type,master_item_id:mi?.id||null,item_name_snapshot:r.item_name,category_snapshot:r.category||mi?.category||null,points_snapshot:r.points||mi?.points||0,occurred_at:r.date,chronology:r.notes||null,recorder_name:r.recorder||null})}}if(incidentRows.length){const a=await sb.from('incidents').insert(incidentRows);if(a.error)throw a.error}if(actionRows.length){const a=await sb.from('student_actions').insert(actionRows);if(a.error)throw a.error}await sb.from('import_history').insert({school_id:school.id,import_type:'student_records',file_name:fileName||'Excel',summary:{found:rows.length,imported:usable.length,unmatched:unmatched.length,new_master:needed.length,incidents:incidentRows.length,sanctions:actionRows.length}});setStatus(`Import selesai: ${usable.length} catatan masuk, ${needed.length} master baru dibuat${unmatched.length?`, ${unmatched.length} baris dilewati karena siswa tidak ditemukan`:''}.`);setRows([]);setFileName('');await reload()}catch(e:any){setStatus(e?.message||'Import gagal. Periksa file lalu coba lagi.')}finally{setBusy(false)}}
 const preview=rows.slice(0,8);
 const matchedCount=rows.filter(findStudent).length;
 return <div className="page"><div className="pageLead"><div><h1>Import & Export</h1><p>Import siswa dan seluruh catatan pelanggaran, prestasi, serta sanksi dari Excel. Master yang belum ada dibuat otomatis.</p></div></div>{status&&<Notice kind={status.includes('selesai')?'success':'warning'}>{status}</Notice>}<div className="importCards"><button className="importCard" onClick={()=>setActive('Data Siswa')}><div className="importIcon"><Users/></div><div><h3>Data Siswa</h3><p>Nama siswa wajib. NIS, kelas, orang tua, dan data lain boleh kosong dan bisa diedit nanti.</p><span>Buka Import Siswa <ChevronRight/></span></div></button><button className="importCard" onClick={()=>setActive('Master Data')}><div className="importIcon"><Database/></div><div><h3>Master Data</h3><p>Import daftar pelanggaran, prestasi, dan sanksi tanpa kode spreadsheet.</p><span>Buka Master Data <ChevronRight/></span></div></button><button className="importCard" onClick={downloadTemplate}><div className="importIcon"><Download/></div><div><h3>Download Template Catatan</h3><p>Workbook resmi berisi sheet Pelanggaran, Prestasi, dan Sanksi.</p><span>Download Excel <Download/></span></div></button></div><div className="panel importWorkspace"><div className="panelTitle"><div><h3>Import Catatan Siswa</h3><p>Pelanggaran, prestasi, dan sanksi langsung masuk ke riwayat siswa.</p></div><span className="badge">Auto-create master</span></div><div className="stepbar"><span className={fileName?'done':''}>1 Upload</span><span className={rows.length?'done':''}>2 Preview</span><span>3 Import</span></div><button className="dropzone" onClick={()=>fileRef.current?.click()}><FileSpreadsheet/><b>{fileName||'Pilih Excel catatan siswa'}</b><span>.xlsx / .xls · sheet Pelanggaran, Prestasi, Sanksi</span></button><input ref={fileRef} hidden type="file" accept=".xlsx,.xls" onChange={e=>e.target.files?.[0]&&readExcel(e.target.files[0])}/>{rows.length>0&&<div className="previewBox"><div className="panelTitle"><div><h3>Preview Import</h3><p>{rows.length} baris ditemukan · {matchedCount} siswa cocok</p></div></div>{preview.map((r:any,i)=><div className="previewRow" key={i}><b>{r.student_name||r.nis}</b><span>{r.type==='violation'?'Pelanggaran':r.type==='achievement'?'Prestasi':'Sanksi'} · {r.item_name} · {r.points} poin</span></div>)}{rows.length>preview.length&&<small>+ {rows.length-preview.length} baris lainnya</small>}</div>}<div className="templateStrip"><div><b>Aturan import</b><span>Siswa dicocokkan lewat NIS, atau Nama + Kelas. Jenis master baru dibuat otomatis.</span></div><button className="ghost actionBtn" onClick={downloadTemplate}><Download/> Template</button></div><div className="modalActions"><button className="primary" disabled={!rows.length||busy} onClick={runImport}><Upload/> {busy?'Mengimport...':'Import Catatan Sekarang'}</button></div></div></div>
}
