'use client';
import {useEffect,useState} from 'react';
import {createClient} from '@supabase/supabase-js';
import {LayoutDashboard,Users,PlusCircle,ClipboardCheck,FileText,Database,Settings,Sun,Moon,Menu,X,Search,LogOut,Trophy,TriangleAlert,GraduationCap,ChevronRight} from 'lucide-react';

const sb=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY!);
const nav=[['Dashboard',LayoutDashboard],['Data Siswa',Users],['Catat Kejadian',PlusCircle],['Pembinaan',ClipboardCheck],['Laporan',FileText],['Master Data',Database],['Pengaturan',Settings]] as const;
export default function Home(){
 const [dark,setDark]=useState(false),[drawer,setDrawer]=useState(false),[active,setActive]=useState('Dashboard'),[session,setSession]=useState<any>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[authMode,setAuthMode]=useState<'login'|'signup'>('login'),[msg,setMsg]=useState(''),[students,setStudents]=useState<any[]>([]),[school,setSchool]=useState<any>(null);
 useEffect(()=>{sb.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)});const {data:{subscription}}=sb.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const {data:s}=await sb.from('schools').select('*').single();setSchool(s);if(s){const {data}=await sb.from('students').select('*').order('name');setStudents(data||[])}}
 async function auth(e:any){e.preventDefault();setMsg('');if(authMode==='login'){const {error}=await sb.auth.signInWithPassword({email,password});if(error)setMsg(error.message)}else{const {data,error}=await sb.auth.signUp({email,password});if(error)return setMsg(error.message);if(data.user){const {error:x}=await sb.from('schools').insert({owner_user_id:data.user.id,name:'Sekolah Baru'});if(x)setMsg(x.message);else setMsg('Akun berhasil dibuat. Silakan masuk.')}}}
 async function logout(){await sb.auth.signOut();setSession(null)}
 if(loading)return <main className="center"><div className="loader"/></main>;
 if(!session)return <main className={'login '+(dark?'dark':'')}><button className="theme floating" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><section className="authCard"><Brand/><div className="authIntro"><h1>{authMode==='login'?'Selamat datang kembali':'Buat akun sekolah'}</h1><p>Sistem disiplin sekolah yang cepat, rapi, dan terintegrasi.</p></div><form onSubmit={auth}><label>Email sekolah<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required placeholder="sekolah@email.com"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required minLength={6} placeholder="••••••••"/></label>{msg&&<p className="error">{msg}</p>}<button className="primary">{authMode==='login'?'Masuk':'Buat Akun'}</button></form><button className="link" onClick={()=>setAuthMode(authMode==='login'?'signup':'login')}>{authMode==='login'?'Belum punya akun sekolah? Buat akun':'Sudah punya akun? Masuk'}</button></section></main>;
 return <div className={dark?'app dark':'app'}><aside className={drawer?'side open':'side'}><div className="sideTop"><Brand/><button className="close" onClick={()=>setDrawer(false)}><X/></button></div><nav>{nav.map(([n,I])=><button key={n} className={active===n?'nav active':'nav'} onClick={()=>{setActive(n);setDrawer(false)}}><I/><span>{n}</span></button>)}</nav><div className="sideFoot"><div className="schoolMini"><div className="avatar">{(school?.name||'S')[0]}</div><div><b>{school?.name||'Sekolah'}</b><small>{school?.academic_year||'2026/2027'}</small></div></div><button className="nav" onClick={logout}><LogOut/><span>Keluar</span></button></div></aside>{drawer&&<div className="backdrop" onClick={()=>setDrawer(false)}/>}<main className="content"><header><button className="hamb" onClick={()=>setDrawer(true)}><Menu/></button><div><h2>{active}</h2><p>{school?.name||'Bantu Beres Disiplin Pro'}</p></div><div className="headerActions"><button className="theme" onClick={()=>setDark(!dark)}>{dark?<Sun/>:<Moon/>}</button><button className="primary small" onClick={()=>setActive('Catat Kejadian')}><PlusCircle/> Catat Kejadian</button></div></header>{active==='Dashboard'?<Dashboard students={students} setActive={setActive}/>:<Module name={active} students={students} school={school} reload={load}/>}</main></div>
}
function Brand(){return <div className="brand"><div className="brandIcon">B</div><div><b>Bantu Beres</b><span>Disiplin Pro</span></div></div>}
function Dashboard({students,setActive}:{students:any[],setActive:any}){return <div className="page"><section className="hero"><div><span className="eyebrow">RINGKASAN SEKOLAH</span><h1>Kelola kedisiplinan dengan lebih mudah.</h1><p>Catat kejadian, pantau perkembangan siswa, dan siapkan laporan dalam satu tempat.</p></div><button className="heroBtn" onClick={()=>setActive('Catat Kejadian')}><PlusCircle/> Catat kejadian baru <ChevronRight/></button></section><section className="stats"><Stat icon={<Users/>} n={students.length} t="Total Siswa"/><Stat icon={<TriangleAlert/>} n="0" t="Pelanggaran Hari Ini"/><Stat icon={<Trophy/>} n="0" t="Prestasi Hari Ini"/><Stat icon={<GraduationCap/>} n="0" t="Perlu Perhatian"/></section><section className="grid"><div className="panel wide"><div className="panelTitle"><div><h3>Aktivitas terbaru</h3><p>Catatan kejadian terbaru akan muncul di sini.</p></div></div><Empty text="Belum ada aktivitas hari ini"/></div><div className="panel"><div className="panelTitle"><div><h3>Akses Cepat</h3><p>Pekerjaan yang sering dilakukan</p></div></div><div className="quick"><button onClick={()=>setActive('Data Siswa')}><Users/> Data siswa <ChevronRight/></button><button onClick={()=>setActive('Master Data')}><Database/> Master data <ChevronRight/></button><button onClick={()=>setActive('Laporan')}><FileText/> Buat laporan <ChevronRight/></button></div></div></section></div>}
function Stat({icon,n,t}:any){return <div className="stat"><div className="statIcon">{icon}</div><div><strong>{n}</strong><span>{t}</span></div></div>}
function Empty({text}:any){return <div className="empty"><div className="emptyIcon"><ClipboardCheck/></div><b>{text}</b><span>Data akan tampil otomatis setelah mulai digunakan.</span></div>}
function Module({name,students,school,reload}:any){const [q,setQ]=useState(''),[show,setShow]=useState(false),[studentName,setStudentName]=useState('');async function addStudent(e:any){e.preventDefault();if(!studentName.trim()||!school)return;await sb.from('students').insert({school_id:school.id,name:studentName.trim()});setStudentName('');setShow(false);reload()}if(name==='Data Siswa')return <div className="page"><div className="toolbar"><div className="search"><Search/><input placeholder="Cari nama siswa atau NIS..." value={q} onChange={e=>setQ(e.target.value)}/></div><button className="primary" onClick={()=>setShow(true)}><PlusCircle/> Tambah Siswa</button></div><div className="panel tablePanel"><div className="panelTitle"><div><h3>Daftar Siswa</h3><p>Nama adalah data wajib. Data lain dapat dilengkapi kapan saja.</p></div><span className="badge">{students.length} siswa</span></div>{students.filter((s:any)=>s.name.toLowerCase().includes(q.toLowerCase())).length?students.filter((s:any)=>s.name.toLowerCase().includes(q.toLowerCase())).map((s:any)=><div className="student" key={s.id}><div className="avatar">{s.name[0]}</div><div className="studentInfo"><b>{s.name}</b><span>{s.nis||'NIS belum diisi'} · {s.class_name||'Kelas belum diisi'}</span></div><ChevronRight/></div>):<Empty text="Belum ada data siswa"/>}</div>{show&&<div className="modalWrap"><form className="modal" onSubmit={addStudent}><h3>Tambah Siswa</h3><p>Cukup masukkan nama. Detail lainnya bisa diedit nanti.</p><label>Nama siswa<input autoFocus value={studentName} onChange={e=>setStudentName(e.target.value)} placeholder="Nama lengkap siswa"/></label><div className="modalActions"><button type="button" className="ghost" onClick={()=>setShow(false)}>Batal</button><button className="primary">Simpan Siswa</button></div></form></div>}</div>;
 return <div className="page"><div className="panel moduleHero"><div className="moduleIcon">{name==='Catat Kejadian'?<PlusCircle/>:name==='Laporan'?<FileText/>:name==='Master Data'?<Database/>:<Settings/>}</div><h2>{name}</h2><p>Modul {name.toLowerCase()} sudah terhubung ke fondasi Bantu Beres Disiplin Pro dan siap digunakan dalam alur sekolah.</p></div></div>}
