'use client';
import {useEffect,useRef,useState} from 'react';
import {Building2,CalendarDays,CheckCircle2,MapPin,Moon,Palette,Save,School,Sun,UserRound,AlertCircle,Upload,Image as ImageIcon,PenLine,Stamp,Loader2} from 'lucide-react';
import {sb} from './client';

function Notice({kind='success',children}:any){return <div className={'notice '+kind}>{kind==='success'?<CheckCircle2/>:<AlertCircle/>}<span>{children}</span></div>}

type AssetKey='logo_url'|'signature_url'|'stamp_url';
const assets=[
 {key:'logo_url' as AssetKey,title:'Logo Sekolah',icon:ImageIcon},
 {key:'signature_url' as AssetKey,title:'Tanda Tangan',icon:PenLine},
 {key:'stamp_url' as AssetKey,title:'Stempel Sekolah',icon:Stamp}
];

export default function StyledSettingsPage({school,reload,dark,setDark}:any){
 const [form,setForm]=useState<any>({});
 const [status,setStatus]=useState('');
 const [busy,setBusy]=useState(false);
 const [uploading,setUploading]=useState<AssetKey|null>(null);
 const [urls,setUrls]=useState<Record<AssetKey,string>>({logo_url:'',signature_url:'',stamp_url:''});
 const refs=useRef<Record<AssetKey,HTMLInputElement|null>>({logo_url:null,signature_url:null,stamp_url:null});
 useEffect(()=>{if(!school)return;setForm({name:school.name||'',principal_name:school.principal_name||'',principal_nip:school.principal_nip||'',npsn:school.npsn||'',address:school.address||'',city:school.city||'',province:school.province||'',postal_code:school.postal_code||'',phone:school.phone||'',email_contact:school.email_contact||'',website:school.website||'',discipline_lead:school.discipline_lead||'',academic_year:school.academic_year||'2026/2027',semester:school.semester||'Ganjil',early_warning_days:school.early_warning_days||30,early_warning_points:school.early_warning_points||15});setUrls({logo_url:school.logo_url||'',signature_url:school.signature_url||'',stamp_url:school.stamp_url||''})},[school]);
 if(!school)return <div className="page"><div className="panel">Memuat pengaturan...</div></div>;
 async function save(e:any){e.preventDefault();setBusy(true);setStatus('');const r=await sb.from('schools').update(form).eq('id',school.id);setBusy(false);if(r.error){setStatus(r.error.message);return}setStatus('Pengaturan sekolah berhasil disimpan.');await reload()}
 async function uploadAsset(key:AssetKey,file:File){const allowed=['image/png','image/jpeg','image/webp'];if(!allowed.includes(file.type)){setStatus('File harus PNG, JPG, JPEG, atau WebP.');return}if(file.size>2*1024*1024){setStatus('Ukuran file maksimal 2 MB.');return}setUploading(key);setStatus('');const ext=(file.name.split('.').pop()||'png').toLowerCase().replace(/[^a-z0-9]/g,'')||'png';const path=`${school.id}/${key}.${ext}`;const up=await sb.storage.from('school-assets').upload(path,file,{upsert:true,contentType:file.type,cacheControl:'3600'});if(up.error){setUploading(null);setStatus(`Upload gagal: ${up.error.message}`);return}const url=sb.storage.from('school-assets').getPublicUrl(path).data.publicUrl+`?v=${Date.now()}`;const db=await sb.from('schools').update({[key]:url}).eq('id',school.id);setUploading(null);if(db.error){setStatus(`File terunggah tetapi profil gagal disimpan: ${db.error.message}`);return}setUrls(v=>({...v,[key]:url}));setStatus(`${key==='logo_url'?'Logo sekolah':key==='signature_url'?'Tanda tangan':'Stempel sekolah'} berhasil diunggah.`);await reload()}
 return <div className="page settingsPage">
  <div className="pageLead settingsLead"><div><span className="eyebrow purple">PENGATURAN SEKOLAH</span><h1>Pengaturan</h1><p>Kelola identitas, kop surat, tahun ajaran, monitoring, dan tampilan.</p></div><div className="settingsBadge"><School/><div><b>{school.name}</b><span>{school.academic_year} · {school.semester}</span></div></div></div>
  {status&&<Notice kind={status.includes('berhasil')?'success':'warning'}>{status}</Notice>}
  <section className="settingCard elevated"><div className="settingCardHead"><div className="settingIcon"><ImageIcon/></div><div><h3>Identitas & Kop Sekolah</h3><p>Upload logo, tanda tangan, dan stempel. File disimpan di Supabase.</p></div></div><div className="assetGrid">{assets.map(a=>{const Icon=a.icon;const url=urls[a.key];return <div className="assetItem" key={a.key}><div className="assetTitle"><span className="assetIcon"><Icon/></span><div><b>{a.title}</b><small>PNG, JPG, JPEG, WebP · maksimal 2 MB</small></div></div><input ref={el=>{refs.current[a.key]=el}} hidden type="file" accept="image/png,image/jpeg,image/webp" onChange={e=>{const f=e.target.files?.[0];if(f)uploadAsset(a.key,f);e.currentTarget.value=''}}/><button type="button" className="assetDrop" disabled={uploading!==null} onClick={()=>refs.current[a.key]?.click()}>{url?<img src={url} alt={a.title}/>:<><Upload/><span>Upload {a.title}</span></>}{uploading===a.key?<em><Loader2 className="spin"/> Mengunggah...</em>:url?<em className="ok"><CheckCircle2/> Tersimpan</em>:<em>Klik untuk memilih file</em>}</button></div>})}</div></section>
  <form className="settingsModern" onSubmit={save}>
   <section className="settingCard elevated"><div className="settingCardHead"><div className="settingIcon"><Building2/></div><div><h3>Profil Sekolah</h3><p>Data utama yang dipakai di seluruh sistem.</p></div></div><div className="formGrid polished"><label className="full">Nama Sekolah<input value={form.name||''} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>NPSN<input value={form.npsn||''} onChange={e=>setForm({...form,npsn:e.target.value})}/></label><label>No. Telepon<input value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></label><label className="full">Alamat<input value={form.address||''} onChange={e=>setForm({...form,address:e.target.value})}/></label><label>Kota / Kabupaten<input value={form.city||''} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Provinsi<input value={form.province||''} onChange={e=>setForm({...form,province:e.target.value})}/></label><label>Kode Pos<input value={form.postal_code||''} onChange={e=>setForm({...form,postal_code:e.target.value})}/></label><label>Email Sekolah<input value={form.email_contact||''} onChange={e=>setForm({...form,email_contact:e.target.value})}/></label><label className="full">Website<input value={form.website||''} onChange={e=>setForm({...form,website:e.target.value})}/></label></div></section>
   <section className="settingCard elevated"><div className="settingCardHead"><div className="settingIcon"><UserRound/></div><div><h3>Penanggung Jawab</h3><p>Informasi kepala sekolah dan BK/kesiswaan.</p></div></div><div className="formGrid polished"><label>Nama Kepala Sekolah<input value={form.principal_name||''} onChange={e=>setForm({...form,principal_name:e.target.value})}/></label><label>NIP Kepala Sekolah<input value={form.principal_nip||''} onChange={e=>setForm({...form,principal_nip:e.target.value})}/></label><label className="full">BK / Kesiswaan<input value={form.discipline_lead||''} onChange={e=>setForm({...form,discipline_lead:e.target.value})}/></label></div></section>
   <section className="settingCard elevated"><div className="settingCardHead"><div className="settingIcon"><CalendarDays/></div><div><h3>Tahun Ajaran & Monitoring</h3><p>Mengatur periode kerja dan parameter deteksi dini.</p></div></div><div className="formGrid polished"><label>Tahun Ajaran<input value={form.academic_year||''} onChange={e=>setForm({...form,academic_year:e.target.value})}/></label><label>Semester<select value={form.semester||'Ganjil'} onChange={e=>setForm({...form,semester:e.target.value})}><option>Ganjil</option><option>Genap</option></select></label><label>Rentang Deteksi Dini (hari)<input type="number" min="1" max="365" value={form.early_warning_days||30} onChange={e=>setForm({...form,early_warning_days:Number(e.target.value)})}/></label><label>Ambang Kenaikan Poin<input type="number" min="0" value={form.early_warning_points||15} onChange={e=>setForm({...form,early_warning_points:Number(e.target.value)})}/></label></div><div className="settingTip"><MapPin/><span>Parameter ini dipakai untuk menandai siswa yang mengalami kenaikan poin cepat.</span></div></section>
   <section className="settingCard elevated"><div className="settingCardHead"><div className="settingIcon"><Palette/></div><div><h3>Tema Tampilan</h3><p>Pilih tema yang nyaman.</p></div></div><div className="themeChoices modern"><button type="button" className={!dark?'selected':''} onClick={()=>setDark(false)}><Sun/><div><b>Tema Terang</b><span>Bersih dan nyaman</span></div></button><button type="button" className={dark?'selected':''} onClick={()=>setDark(true)}><Moon/><div><b>Tema Gelap</b><span>Nyaman malam hari</span></div></button></div></section>
   <div className="settingsSaveBar"><div><b>Perubahan belum disimpan?</b><span>Tekan simpan agar data dipakai pada seluruh modul.</span></div><button className="primary" disabled={busy}><Save/>{busy?'Menyimpan...':'Simpan Pengaturan'}</button></div>
  </form>
  <style jsx>{`.assetGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.assetItem{min-width:0}.assetTitle{display:flex;gap:10px;align-items:center;margin-bottom:10px}.assetTitle b{display:block}.assetTitle small{display:block;font-size:11px;opacity:.7;margin-top:3px}.assetIcon{width:36px;height:36px;border-radius:10px;display:grid;place-items:center;background:#eef4ff;color:#285cff}.assetIcon svg{width:18px}.assetDrop{width:100%;min-height:170px;border:1px dashed #cbd5e1;border-radius:14px;background:#f8fafc;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;cursor:pointer;padding:10px;overflow:hidden}.assetDrop img{width:100%;height:120px;object-fit:contain}.assetDrop>svg{width:30px}.assetDrop em{font-style:normal;font-size:12px;opacity:.7;display:flex;align-items:center;gap:5px}.assetDrop em.ok{color:#159447;opacity:1}.spin{animation:spin 1s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:900px){.assetGrid{grid-template-columns:1fr}}`}</style>
 </div>
}
